// Generated by CoffeeScript 1.8.0
(function() {
  var define_controller;

  define('account', function(require) {
    var doc_plugin;
    return doc_plugin = {
      type: 'plugin',
      title: 'Account',
      anchor: '#/account',
      _models: {},
      name: 'account',
      version: 1.0,
      order: -14,
      icon: 'icon-cog',
      init: function() {
        foundry.initialized(this.name);
        define_controller();
      }
    };
  });

  define_controller = function() {
    return angular.module('foundry').controller('AccountController', [
      '$scope', '$rootScope', '$foundry', '$filter', function($scope, $rootScope, $foundry, $filter) {
        var plan_to_usernumber;
        $rootScope.breadcum = 'Account';
        $scope.current_user_role = foundry._user_list[foundry._current_user.id].role;
        plan_to_usernumber = {
          0: "10",
          1: "25",
          2: "50",
          3: "infinite"
        };
        $scope.get_plan = function() {
          return foundry._owner_plan;
        };
        $scope.usernumber = plan_to_usernumber[foundry._owner_plan];
        $scope.users = Nimbus.keys(foundry._user_list).length;
        $scope.is_current_plan = function(plan) {
          if (plan === $scope.get_plan()) {
            return 'current';
          } else if (plan > $scope.get_plan()) {
            return 'up';
          } else {
            return 'down';
          }
        };
        if (foundry.get_setting("email") == null) {
          $scope.setting_email = true;
        } else {
          $scope.setting_email = foundry.get_setting("email");
        }
        $scope.setting_email_change = function(status) {
          console.log("called");
          return foundry.set_setting("email", status);
        };
        return window.a_scope = $scope;
      }
    ]);
  };

}).call(this);
