// Generated by CoffeeScript 1.8.0
(function() {
  define('core/analytic', function() {
    var api, get_owner_space_count, init, send_login_event, send_owner_event, send_user_event;
    init = function() {
      var count;
      ga('create', 'UA-55223184-1', {
        'userId': foundry._current_user.email
      });
      ga('require', 'displayfeatures');
      ga('set', 'dimension1', foundry._current_user.email);
      ga('set', 'dimension2', Nimbus.realtime.c_file.title);
      ga('set', 'dimension3', Nimbus.realtime.c_file.owners[0].emailAddress + ':' + Nimbus.realtime.c_file.owners[0].displayName);
      count = foundry._models.User.all();
      ga('set', 'dimension4', count);
      return ga('send', 'pageview');
    };
    get_owner_space_count = function() {
      var count, space, _i, _len, _ref;
      count = 0;
      _ref = Nimbus.realtime.app_files;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        space = _ref[_i];
        if (space.owners[0].permissionId === foundry._current_user.id) {
          count++;
        }
      }
      return count;
    };
    send_owner_event = function(data) {
      var count;
      if (!ga) {
        return;
      }
      count = get_owner_space_count();
      return ga('send', 'event', 'forum_owner_operation:' + data.email, 'create_workspace:' + data.name, count);
    };
    send_user_event = function(data) {
      var count;
      if (!ga) {
        return;
      }
      count = foundry._models.User.all().length;
      return ga('send', 'event', 'forum_owner_operation:' + data.email, 'share_workspace:' + data.user, count);
    };
    send_login_event = function(data) {};
    return api = {
      init: function() {
        return init();
      },
      owner: function(data) {
        return send_owner_event(data);
      },
      user: function(data) {
        return send_user_event(data);
      },
      login: function(data) {
        return send_login_event(data);
      }
    };
  });

}).call(this);
